model_list:
  - model_name: "*"
    litellm_params:
      model: nvidia_nim/deepseek-ai/deepseek-v4-flash
      api_base: https://integrate.api.nvidia.com/v1
      api_key: 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

litellm_settings:
  drop_params: true